"""initial schema

Revision ID: d2e72bef0500
Revises: 
Create Date: 2026-09-10 08:30:55.986147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2e72bef0500'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='running', nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_changed', sa.Integer(), nullable=True),
    sa.Column('watermark', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_pickup', 'jobs', ['status', 'run_after'], unique=False)
    op.create_table('raw_ingestions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_ingestions_source_id', 'raw_ingestions', ['source', 'source_id', sa.literal_column('fetched_at DESC')], unique=False)
    op.create_table('recalls',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=False),
    sa.Column('product_name_normalized', sa.Text(), nullable=False),
    sa.Column('hazard_description', sa.Text(), nullable=True),
    sa.Column('hazard_classification', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('date_initiated', sa.Date(), nullable=True),
    sa.Column('date_terminated', sa.Date(), nullable=True),
    sa.Column('geographic_scope', sa.Text(), nullable=True),
    sa.Column('raw_ingestion_id', sa.BigInteger(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_ingestion_id'], ['raw_ingestions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id')
    )
    op.create_index('idx_recalls_date_initiated', 'recalls', ['date_initiated'], unique=False)
    op.create_index('idx_recalls_name_trgm', 'recalls', ['product_name_normalized'], unique=False, postgresql_using='gin', postgresql_ops={'product_name_normalized': 'gin_trgm_ops'})
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('recall_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('recall_id', sa.UUID(), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recall_id'], ['recalls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recall_upcs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('recall_id', sa.UUID(), nullable=False),
    sa.Column('upc', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['recall_id'], ['recalls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recall_upcs_upc', 'recall_upcs', ['upc'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('image_s3_key', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ocr_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('brand_extracted', sa.Text(), nullable=True),
    sa.Column('product_name_extracted', sa.Text(), nullable=False),
    sa.Column('product_name_normalized', sa.Text(), nullable=False),
    sa.Column('upc', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('unit_price', sa.Numeric(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_receipt_items_name_trgm', 'receipt_items', ['product_name_normalized'], unique=False, postgresql_using='gin', postgresql_ops={'product_name_normalized': 'gin_trgm_ops'})
    op.create_index('idx_receipt_items_upc', 'receipt_items', ['upc'], unique=False)
    op.create_table('match_candidates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('receipt_item_id', sa.UUID(), nullable=False),
    sa.Column('recall_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('match_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending_review', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recall_id'], ['recalls.id'], ),
    sa.ForeignKeyConstraint(['receipt_item_id'], ['receipt_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_item_id', 'recall_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('match_candidate_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), server_default='email', nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_candidate_id'], ['match_candidates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('match_candidates')
    op.drop_index('idx_receipt_items_upc', table_name='receipt_items')
    op.drop_index('idx_receipt_items_name_trgm', table_name='receipt_items', postgresql_using='gin', postgresql_ops={'product_name_normalized': 'gin_trgm_ops'})
    op.drop_table('receipt_items')
    op.drop_table('receipts')
    op.drop_index('idx_recall_upcs_upc', table_name='recall_upcs')
    op.drop_table('recall_upcs')
    op.drop_table('recall_history')
    op.drop_table('users')
    op.drop_index('idx_recalls_name_trgm', table_name='recalls', postgresql_using='gin', postgresql_ops={'product_name_normalized': 'gin_trgm_ops'})
    op.drop_index('idx_recalls_date_initiated', table_name='recalls')
    op.drop_table('recalls')
    op.drop_index('idx_raw_ingestions_source_id', table_name='raw_ingestions')
    op.drop_table('raw_ingestions')
    op.drop_index('idx_jobs_pickup', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('ingestion_runs')
    op.drop_table('households')
    # ### end Alembic commands ###
    op.execute('DROP EXTENSION IF EXISTS pg_trgm')
